### ISSUE TITLE
Crashes on Opening a File (Aarch64)

### ISSUE THREAD

**Issue by Saroufim** [NickvisionApps/Denaro#465]
When selecting an nmoney file to open, the application crashes. If a new one is created, the application would still crash. This is only happening on my Aarch64 device. On x86_64 everything runs as it should. I tried switching to the beta branch but the error was still there.
Denaro is installed from Flathub and the device is running PostmarketOS.

**Comment by nlogozzo** [comment]
Can you run the app via the terminal, flatpak run org.nickvision.money, and see if you get any error message?

**Comment by Saroufim** [comment]
```

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 19:49:53.307: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 19:49:53.307: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed
Unhandled exception. System.ArgumentException: There is no region associated with the Invariant Culture (Culture ID: 0x7F). (Parameter 'name')
   at System.Globalization.RegionInfo..ctor(String name)
   at NickvisionMoney.Shared.Controllers.AccountViewController.get_CultureForNumberString() in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 203
   at NickvisionMoney.GNOME.Views.AccountView.CreateGroupRow(Group group, Nullable`1 index) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 362
   at NickvisionMoney.Shared.Controllers.AccountViewController.StartupAsync() in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 477
   at NickvisionMoney.GNOME.Views.AccountView.StartupAsync() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 540
   at NickvisionMoney.GNOME.Views.MainWindow.AccountAdded(Object sender, EventArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/MainWindow.cs:line 295
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by nlogozzo** [comment]
Ah looks like an issue with your locale settings on your system.

If you go into the terminal and type `locale` what does it print?

**Comment by Saroufim** [comment]
`locale: not found`
Is this one of Alpine's particularities?

**Comment by nlogozzo** [comment]
Sounds like it.

Maybe this can help: https://github.com/gliderlabs/docker-alpine/issues/144

On Denaro's side we can maybe use en-US as default region if there is no culture on the system, to prevent the crash.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.5.0-rc1
