### ISSUE TITLE
Cannot create new account on another disk in my machine

### ISSUE THREAD

**Issue by luizgfranca** [NickvisionApps/Denaro#480]
### Problem description

I use a laptop with 2 internal disks, and usually save all my data in my hard disk (SATA) and leave only system stuff on my Nvme SSD.

What do i do to reproduce the problem:
- Open Denaro flatpak
- Select "New Account"
- Select folder on witch the disk is mounted (in my case `/data`)
- Choose it or any subfolder to save

Stack trace of the error:

```
(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 23:25:38.747: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed
Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 10: 'disk I/O error'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at NickvisionMoney.Shared.Models.Account.LoadAsync() in /run/build/org.nickvision.money/NickvisionMoney.Shared/Models/Account.cs:line 326
   at NickvisionMoney.Shared.Controllers.AccountViewController.StartupAsync() in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 462
   at NickvisionMoney.GNOME.Views.AccountView.StartupAsync() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 540
   at NickvisionMoney.GNOME.Views.MainWindow.AccountAdded(Object sender, EventArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/MainWindow.cs:line 295
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

```
#### Important details: 
- The application crashes when the error happen
- The `.nmoney` file is created in the chosen path, but accessing it with sqlite i verified it has no tables.
- Trying to open the same file using "Open Account" results in the same error
- When i try to save it in my Linux installation disk the process works flawlessly.

### Contextual information:

I installed Denaro from flathub:
version 2023.4.1

My system: 
Kubuntu 20.10
KDE Plasma 5.25.5
Window system: X11
Flatpak version: 1.14.0

My machine information:
AMD Ryzen 7 4800H
16GB RAM 
NVIDIA driver version: 515.105.01

My machine disk structure is as follows:
```
$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
# ommited snap loopback partitions
sda           8:0    0 931,5G  0 disk 
├─sda1        8:1    0 895,3G  0 part /data
├─sda2        8:2    0     1M  0 part 
├─sda3        8:3    0  30,2G  0 part 
└─sda4        8:4    0     6G  0 part 
nvme0n1     259:0    0 238,5G  0 disk 
├─nvme0n1p1 259:1    0    16M  0 part 
├─nvme0n1p2 259:2    0    80G  0 part 
├─nvme0n1p3 259:3    0     6G  0 part /boot/efi
└─nvme0n1p4 259:4    0 152,5G  0 part /var/snap/firefox/common/host-hunspell

```

Here is the content of my /etc/fstab:
```
$ cat /etc/fstab 
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/nvme0n1p4 during installation
UUID=4a15b568-2e80-4b01-8acb-6f241e36f020 /               ext4    errors=remount-ro 0       1
# /boot/efi was on /dev/nvme0n1p3 during installation
UUID=E01A-77AC  /boot/efi       vfat    umask=0077      0       1

UUID=2AB2C0797364739B    /data  ntfs    defaults        0       2
```

As mentioned above the disk i'm trying to use is the one mounted in `/data`

Thank you in advance! I tried to provide all relevant information I could think, if you need anything more I will be happy to help.

**Comment by nlogozzo** [comment]
Because you installed the app via flatpak, the application is sandboxed and doesn't have access to all the files on your disk.

You need to use an application such as [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) and give Denaro access to your full file system to store files on external disks/other locations other than home.

**Comment by fsobolev** [comment]
> You need to use an application such as [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) and give Denaro access to your full file system to store files on external disks/other locations other than home.

Not necessary full access, if the path to desired folder is permanent it can be used too (in this case `/data`).
