### ISSUE TITLE
Unable To Export PDFs with Receipts

### ISSUE THREAD

**Issue by nlogozzo** [NickvisionApps/Denaro#484]
```
QuestPDF.Drawing.Exceptions.DocumentLayoutException: Composed layout generates infinite document. This may happen in two cases. 1) Your document and its layout configuration is correct but the content takes more than 250 pages. In this case, please increase the value QuestPDF.Settings.DocumentLayoutExceptionThreshold static property. 2) The layout configuration of your document is invalid. Some of the elements require more space than is provided.Please analyze your documents structure to detect this element and fix its size constraints.
   at QuestPDF.Drawing.DocumentGenerator.<RenderPass>g__ThrowLayoutException|6_1[TCanvas](<>c__DisplayClass6_0`1&)
   at QuestPDF.Drawing.DocumentGenerator.RenderPass[TCanvas](PageContext pageContext, TCanvas canvas, Container content, DebuggingState debuggingState)
   at QuestPDF.Drawing.DocumentGenerator.RenderDocument[TCanvas](TCanvas canvas, IDocument document)
   at QuestPDF.Drawing.DocumentGenerator.GeneratePdf(Stream stream, IDocument document)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, Stream stream)
   at QuestPDF.Fluent.GenerateExtensions.GeneratePdf(IDocument document, String filePath)
   at NickvisionMoney.Shared.Models.Account.ExportToPDF(String path, ExportMode exportMode, List`1 filteredIds, String password) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Models/Account.cs:line 1561
```

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.5.0-rc1
