### ISSUE TITLE
Denaro can't open a file that was moved

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/Denaro#485]
Steps to reproduce:
1. Open any account to ensure it's working
2. Create a copy of the file (name it whatever you want, it will still open after renaming)
3. Move the copied file to any other directory
4. Open the file. No matter whether you open it from terminal or file manager, Denaro will not load it on start. Opening a file in app using "Open File" leads to crash:

```
Unhandled exception. [Microsoft.Data](http://microsoft.data/).Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at [Microsoft.Data](http://microsoft.data/).Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at [Microsoft.Data](http://microsoft.data/).Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at [Microsoft.Data](http://microsoft.data/).Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at [Microsoft.Data.Sqlite.SqliteConnection.Open](http://microsoft.data.sqlite.sqliteconnection.open/)()
   at NickvisionMoney.Shared.Models.Account.get\_IsEncrypted() in /var/home/user/Проекты/Nickvision/Denaro/NickvisionMoney.Shared/Models/Account.cs:line 123
   at NickvisionMoney.Shared.Controllers.AccountViewController.get\_AccountNeedsPassword() in /var/home/user/Проекты/Nickvision/Denaro/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 87
   at NickvisionMoney.Shared.Controllers.MainWindowController.AddAccountAsync(String path, Boolean showOpenedNotification, String password) in /var/home/user/Проекты/Nickvision/Denaro/NickvisionMoney.Shared/Controllers/MainWindowController.cs:line 220
   at NickvisionMoney.GNOME.Views.MainWindow.<>c__DisplayClass61\_0.<<OnOpenAccount>b__0>d.MoveNext() in /var/home/user/Проекты/Nickvision/Denaro/NickvisionMoney.GNOME/Views/MainWindow.cs:line 385
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b\_\_128\_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

The file still can be opened in DB Browser and seems like there's no issues with the file content.

**Comment by nlogozzo** [comment]
Can't reproduce.
#499 will solve any remaining issue.
