### ISSUE TITLE
Adding receipts causes Denaro to crash

### ISSUE THREAD

**Issue by JoseBritto** [NickvisionApps/Denaro#649]
This is a bug I got first a while ago when I first tried out Denaro. I couldn't file a bug report at that time. Today I opened Denaro in a long time and was surprised to find out that the same bug was still there and I couldn't find any reports of this issue here. This makes me believe that this is something that has to do with my particular setup.  Writing this here just incase it isn't.

### Steps to reproduce
1. Create a new checking account
2. Add an expense
3. Write a name & amount and upload a jpg image as the receipt.
4. Click the view button. *(This didn't work for me the first time, but that was because I had restricted Denaro's permission to Documents directory only. Resetting all permissions to default made this work.)*
5. Click Add
6. Open the transaction again.
7. Now sometimes it opens but you sometimes it crashes.
8. If it opens try viewing the reciept and either it crashes or does nothing when clicking the view button.
9. Sometimes when it crashes, there is no logs output in the terminal but most times there is.

Here is the output printed when it crashes:
```
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Image`1'.
   at SixLabors.ImageSharp.Image.ThrowObjectDisposedException(Type type)
   at SixLabors.ImageSharp.Image.EnsureNotDisposed()
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Clone(Image source, Configuration configuration, Action`1 operation)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Clone(Image source, Action`1 operation)
   at NickvisionMoney.Shared.Models.Transaction.Clone() in /run/build/org.nickvision.money/NickvisionMoney.Shared/Models/Transaction.cs:line 163
   at NickvisionMoney.Shared.Controllers.TransactionDialogController..ctor(Transaction transaction, Dictionary`2 transactions, Dictionary`2 groups, Boolean canCopy, String transactionDefaultColor, CultureInfo cultureNumber, CultureInfo cultureDate) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/TransactionDialogController.cs:line 105
   at NickvisionMoney.Shared.Controllers.AccountViewController.CreateTransactionDialogController(UInt32 id) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/AccountViewController.cs:line 522
   at NickvisionMoney.GNOME.Views.AccountView.EditTransaction(Object sender, UInt32 id) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 884
   at NickvisionMoney.GNOME.Controls.TransactionRow.Edit(Button sender, EventArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Controls/TransactionRow.cs:line 171
   at GObject.Signal`1.<>c__DisplayClass11_0.<Connect>b__0(Value returnValue, Value[] parameters)
```

This warning is also printed every time Denaro starts up, so I don't think its related but here it is anyway:
```

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 16:29:49.551: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 16:29:49.551: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed
```
 
App version: 2023.6.2 (flatpak)
 OS: EndeavourOS
 DE: Gnome 44.3

*PS: I saw that there was a new stable release 8 hours ago but flathub hasn't picked up on it yet (atleast for me). I tried using the one from flathub-beta (2023.8.0) and it doesn't crash or produce any logs when trying to view the receipt, but still won't show it.*

Edit:
Adding the troubleshotting info from the app here:
```
org.nickvision.money
2023.6.2
GTK 4.10.4
libadwaita 1.3.3
Flatpak
en-CA
LANG=en_CA.UTF-8
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC=en_CA.UTF-8
LC_TIME=en_CA.UTF-8
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY=en_CA.UTF-8
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER=en_CA.UTF-8
LC_NAME=en_CA.UTF-8
LC_ADDRESS=en_CA.UTF-8
LC_TELEPHONE=en_CA.UTF-8
LC_MEASUREMENT=en_CA.UTF-8
LC_IDENTIFICATION=en_CA.UTF-8
LC_ALL=
```

**Comment by JoseBritto** [comment]
I think I found where the bug is. Although I could be wrong

In TransactionDialog.cs line 129 _receiptPath is set to null
On line 430 Validate() is called.
Line 485 in Validate method is this line
```       
 var checkStatus = _controller.UpdateTransaction(date, _descriptionRow.GetText(), _incomeButton.GetActive() ? TransactionType.Income : TransactionType.Expense, (int)_repeatIntervalRow.GetSelected(), groupObject.GetString(), _colorButton.GetExtRgba().ToString(), _colorDropDown.GetSelected() == 0, tags, _amountRow.GetText(), _receiptPath, repeatEndDate, gtk_text_buffer_get_text(_notesView.GetBuffer().Handle, ref iterStart, ref iterEnd, false));
```
which calls UpdateTransaction with this null _receiptPath which in turn sets the Transaction.Receipt to null.

This is what I found going line by line using a debugger.

**Comment by JoseBritto** [comment]
Commenting out the Validate call makes the bug go away.
So maybe adding a bool to the Validate method to skip over the receipt might help? I'm not at all familiar with this codebase so I'm not sure whats the best solution is here.

**Comment by nlogozzo** [comment]
I'll take a look at it as soon as I get home...thanks for pointing out the exact line !!

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.8.1-rc1

*should be on flathub beta soon...whenever gnome gitlab is up again*
