### ISSUE TITLE
Index was out of range error crashes Denaro

### ISSUE THREAD

**Issue by sabriunal** [NickvisionApps/Denaro#655]
Hi, I got this error while I was checking my translation.

It occured when I click a button.

- Version: 9157f69f2cb2c2c9193dfdc1e9f36ebf7690c690 build using flatpak-builder as Flatpak.
- OS: Ubuntu 23.04

[money.webm](https://github.com/NickvisionApps/Denaro/assets/6218679/987f5b37-d426-41d7-9754-67bbb8ef0e7f)

```
flatpak run --verbose org.nickvision.money

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 17:42:52.949: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 17:42:52.949: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed
UnhandledException - unhandled exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at NickvisionMoney.GNOME.Views.AccountView.OnDateRangeStartYearChanged() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 1252
   at NickvisionMoney.GNOME.Views.AccountView.<.ctor>b__69_21(Object sender, NotifySignalArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 207
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)

```

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.8.1-rc1

*should be on flathub beta soon...whenever gnome gitlab is up again*
