### ISSUE TITLE
Crash when transfering money to another account

### ISSUE THREAD

**Issue by Krindog7337** [NickvisionApps/Denaro#671]
Everytime i want to transfer money to another account it's just crashed

```
UnhandledException - unhandled exception: System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown. (Parameter 'ordinal')
Actual value was 13.
   at Microsoft.Data.Sqlite.SqliteDataRecord.GetSqliteType(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteDataRecord.IsDBNull(Int32 ordinal)
   at NickvisionMoney.Shared.Models.AccountMetadata.LoadFromAccountFile(String path, String password) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Models/AccountMetadata.cs:line 196
   at NickvisionMoney.Shared.Controllers.TransferDialogController.UpdateTransfer(String destPath, String destPassword, String amountString, String sourceConversionAmountString, String destConversionAmountString) in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/TransferDialogController.cs:line 156
   at NickvisionMoney.GNOME.Views.TransferDialog.Validate() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/TransferDialog.cs:line 135
   at NickvisionMoney.GNOME.Views.TransferDialog.<.ctor>b__21_1(Object sender, NotifySignalArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/TransferDialog.cs:line 61
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)
```

**Comment by JoseBritto** [comment]
There is another related issue. If this exception doesn't crash Denaro, another race condition probably will. 

Here StartupAsync is called explicitly and also by the event called from the MainWindow:
https://github.com/NickvisionApps/Denaro/blob/4efc3fa134bce1de81ccd746a6d668ed767e3b93/NickvisionMoney.Shared/Controllers/MainWindowController.cs#L384-L386

https://github.com/NickvisionApps/Denaro/blob/4efc3fa134bce1de81ccd746a6d668ed767e3b93/NickvisionMoney.GNOME/Views/MainWindow.cs#L285-L298
I'm gonna try to make a PR addressing both

**Comment by JoseBritto** [comment]
Also this current bug occurs only when opening an old nmoney file without the "CustomCurrencyAmountStyle" field. This is the problematic line:
https://github.com/NickvisionApps/Denaro/blob/4efc3fa134bce1de81ccd746a6d668ed767e3b93/NickvisionMoney.Shared/Models/AccountMetadata.cs#L198

**Comment by nlogozzo** [comment]
> Edit: Seems like OP's account doesn't have fields from ShowTagsList. I was getting errors on 15th field but the original error message shows 13.

Yes this is the issue

> Maybe consider adding a version field to metadata and use that to decide on what logic to use to parse the data? 🤔

We just need to add the code that updates the metadata table from account here as well...

**Comment by nlogozzo** [comment]
> We just need to add the code that updates the metadata table from account here as well...

See we want to ensure that all accounts opened in the latest version of Denaro always have the latest changes

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.9.0
