### ISSUE TITLE
Application Crashes When Opening Account Settings Window

### ISSUE THREAD

**Issue by OssNass** [NickvisionApps/Denaro#679]
I just started to use Denaro.

I have created a new saving account, and after the wizard is done, I try to check the account settings and the application just crashes.

Furthermore, I am using the latest Flatpak version with Fedora 38

The error message is the following:
```UnhandledException - unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GLib.Internal.StringArrayNullTerminatedSafeHandle..ctor(String[] array)
   at Gtk.StringList.New(String[] strings)
   at NickvisionMoney.GNOME.Views.AccountSettingsDialog.Validate() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountSettingsDialog.cs:line 380
   at NickvisionMoney.GNOME.Views.AccountSettingsDialog..ctor(Builder builder, AccountSettingsDialogController controller, Window parent) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountSettingsDialog.cs:line 326
   at NickvisionMoney.GNOME.Views.AccountSettingsDialog..ctor(AccountSettingsDialogController controller, Window parent) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountSettingsDialog.cs:line 337
   at NickvisionMoney.GNOME.Views.AccountView.AccountSettings(SimpleAction sender, EventArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 849
   at GObject.Signal`2.<>c__DisplayClass11_0.<Connect>b__0(Value returnValue, Value[] parameters)
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)
```

**Comment by Hyperspeed1313** [comment]
Same setup, exact same problem, very similar output:

```
UnhandledException - unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GLib.Internal.StringArrayNullTerminatedSafeHandle..ctor(String[] array)
   at Gtk.StringList.New(String[] strings)
   at NickvisionMoney.GNOME.Views.AccountSettingsDialog.Validate() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountSettingsDialog.cs:line 380
   at NickvisionMoney.GNOME.Views.AccountSettingsDialog..ctor(Builder builder, AccountSettingsDialogController controller, Window parent) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountSettingsDialog.cs:line 326
   at NickvisionMoney.GNOME.Views.AccountSettingsDialog..ctor(AccountSettingsDialogController controller, Window parent) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountSettingsDialog.cs:line 337
   at NickvisionMoney.GNOME.Views.AccountView.AccountSettings(SimpleAction sender, EventArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/AccountView.cs:line 849
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)
```

**Comment by fsobolev** [comment]
Looks like this and #680 are the same bug

**Comment by nlogozzo** [comment]
Will look into and confirm if it's the same. I'll just close them all in the same PR...i'll make one now to fix all these bugs

**Comment by nlogozzo** [comment]
I believe this is https://github.com/NickvisionApps/Denaro/issues/644#issuecomment-1694542733 which was fixed in `main`...

Could you install this `.flatpak` file and run it and confirm if it's fixed or not: https://github.com/NickvisionApps/Denaro/actions/runs/6033236519
Here are the commands to run after you extract the zip:
```
flatpak install org.nickvision.money.flatpak
flatpak run org.nickvision.money//master
```
when you are done testing uninstall with `flatpak uninstall org.nickvision.money//master`

**Comment by nlogozzo** [comment]
If that build works, I'll release an update with this as a hot fix

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.9.0

**Comment by Hyperspeed1313** [comment]
A bit late getting back but can confirm V2023.9.2 release has this fixed.
