### ISSUE TITLE
Crashes when turning on and off custom currency in account wizard

### ISSUE THREAD

**Issue by Krindog7337** [NickvisionApps/Denaro#680]
[Screencast from 2023-09-01 22-52-27.webm](https://github.com/NickvisionApps/Denaro/assets/92032579/7906ee75-6f20-4103-b3be-6a6093851e95)

log :
```
UnhandledException - unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GLib.Internal.StringArrayNullTerminatedSafeHandle..ctor(String[] array)
   at Gtk.StringList.New(String[] strings)
   at NickvisionMoney.GNOME.Views.NewAccountDialog.ValidateCurrency() in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/NewAccountDialog.cs:line 385
   at NickvisionMoney.GNOME.Views.NewAccountDialog.<.ctor>b__38_3(Object sender, NotifySignalArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/NewAccountDialog.cs:line 113
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)

```

**Comment by nlogozzo** [comment]
I believe this is https://github.com/NickvisionApps/Denaro/issues/644#issuecomment-1694542733 which was fixed in `main`...

Could you install this `.flatpak` file and run it and confirm if it's fixed or not: https://github.com/NickvisionApps/Denaro/actions/runs/6033236519
Here are the commands to run after you extract the zip:
```
flatpak install org.nickvision.money.flatpak
flatpak run org.nickvision.money//master
```
when you are done testing uninstall with `flatpak uninstall org.nickvision.money//master`

**Comment by nlogozzo** [comment]
If that build works, I'll release an update with this as a hot fix

**Comment by Krindog7337** [comment]
> I believe this is [#644 (comment)](https://github.com/NickvisionApps/Denaro/issues/644#issuecomment-1694542733) which was fixed in `main`...
> 
> Could you install this `.flatpak` file and run it and confirm if it's fixed or not: https://github.com/NickvisionApps/Denaro/actions/runs/6033236519 Here are the commands to run after you extract the zip:
> 
> ```
> flatpak install org.nickvision.money.flatpak
> flatpak run org.nickvision.money//master
> ```
> 
> when you are done testing uninstall with `flatpak uninstall org.nickvision.money//master`

It works now

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Denaro/releases/tag/2023.9.0
