### ISSUE TITLE
New Account button breaks application

### ISSUE THREAD

**Issue by jcamposz** [NickvisionApps/Denaro#721]
When the button "New Accout" is clicked , the application crashes with:

`(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 12:15:26.325: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionMoney.GNOME:2): Gtk-CRITICAL **: 12:15:26.325: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed
UnhandledException - unhandled exception: System.Globalization.CultureNotFoundException: Culture is not supported. (Parameter 'name')
ca-ES@valencia is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at NickvisionMoney.Shared.Controllers.NewAccountDialogController.get_ReportedCurrencyString() in /run/build/org.nickvision.money/NickvisionMoney.Shared/Controllers/NewAccountDialogController.cs:line 113
   at NickvisionMoney.GNOME.Views.NewAccountDialog..ctor(Builder builder, NewAccountDialogController controller, Window parent) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/NewAccountDialog.cs:line 222
   at NickvisionMoney.GNOME.Views.NewAccountDialog..ctor(NewAccountDialogController controller, Window parent) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/NewAccountDialog.cs:line 230
   at NickvisionMoney.GNOME.Views.MainWindow.OnNewAccount(SimpleAction sender, EventArgs e) in /run/build/org.nickvision.money/NickvisionMoney.GNOME/Views/MainWindow.cs:line 309
   at GObject.Signal`2.<>c__DisplayClass11_0.<Connect>b__0(Value returnValue, Value[] parameters)
   at GObject.Closure.InternalCallback(IntPtr closure, IntPtr returnValuePtr, UInt32 nParamValues, ValueData[] paramValuesData, IntPtr invocationHint, IntPtr userData)
`

Denaro Version 2030.9.2

**Comment by nlogozzo** [comment]
Could you open the About dialog,  go to troubleshooting, and debug information and copy and paste that here.

**Comment by jcamposz** [comment]
org.nickvision.money
2023.9.2
GTK 4.10.5
libadwaita 1.3.5
Flatpak
ca-ES
LANG=ca_ES.UTF-8
LC_CTYPE="ca_ES.UTF-8"
LC_NUMERIC=ca_ES.UTF-8@valencia
LC_TIME=ca_ES.UTF-8@valencia
LC_COLLATE="ca_ES.UTF-8"
LC_MONETARY=ca_ES.UTF-8@valencia
LC_MESSAGES="ca_ES.UTF-8"
LC_PAPER=ca_ES.UTF-8@valencia
LC_NAME="ca_ES.UTF-8"
LC_ADDRESS="ca_ES.UTF-8"
LC_TELEPHONE="ca_ES.UTF-8"
LC_MEASUREMENT=ca_ES.UTF-8@valencia
LC_IDENTIFICATION="ca_ES.UTF-8"
LC_ALL=

**Comment by nlogozzo** [comment]
> org.nickvision.money
> 2023.9.2
> GTK 4.10.5
> libadwaita 1.3.5
> Flatpak
> ca-ES
> LANG=ca_ES.UTF-8
> LC_CTYPE="ca_ES.UTF-8"
> LC_NUMERIC=ca_ES.UTF-8@valencia
> LC_TIME=ca_ES.UTF-8@valencia
> LC_COLLATE="ca_ES.UTF-8"
> LC_MONETARY=ca_ES.UTF-8@valencia
> LC_MESSAGES="ca_ES.UTF-8"
> LC_PAPER=ca_ES.UTF-8@valencia
> LC_NAME="ca_ES.UTF-8"
> LC_ADDRESS="ca_ES.UTF-8"
> LC_TELEPHONE="ca_ES.UTF-8"
> LC_MEASUREMENT=ca_ES.UTF-8@valencia
> LC_IDENTIFICATION="ca_ES.UTF-8"
> LC_ALL=
> 

Got it thanks! 

Note to team: We need to turn the `@` into `-` so the final culture C# reads becomes `ca-es-valencia` which is valid whereas `ca-es@valencia` is not.
