### ISSUE TITLE
Open multiple nmoney files at once

### ISSUE THREAD

**Issue by Vigilaterr** [NickvisionApps/Denaro#809]
# Issue

I have 8 accounts with transactions between them. And to correctly see whole finansual picture I have to open all 8 of them one by one within the app. I want to reduce time to open multiple accounts.

# What I tryed and how it fail

1. As I try to open nmoney file from file manager or terminal I have message "This application can not open files." This true for AUR and Flatpak version.
2. Drag and drop on Denaro start page nmoney files led to app crash. Error message in terminal:
```
Process terminated. A callback was made on a garbage collected delegate of type 'GObject-2.0!GObject.Internal.ToggleNotify::Invoke'.
Repeat 2 times:
--------------------------------
   at GObject.Internal.Object.RemoveToggleRef(IntPtr, GObject.Internal.ToggleNotify, IntPtr)
--------------------------------
   at GObject.Internal.ObjectMapper+ToggleRef.Dispose()
   at GObject.Internal.ObjectMapper.Unmap(IntPtr)
   at GObject.Internal.ObjectHandle.ReleaseHandle()
   at System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean)
   at System.Runtime.InteropServices.SafeHandle.Finalize()
```
# Request

PLease, add an options to open files from file manager or terminal
OR
Add an option to open multiple accounts (nmoney files) from filepicker within the app

**Comment by JoseBritto** [comment]
Hello, Sorry for the late response. I tried dragging and dropping multiple nmoney files, but it doesnt seem to crash for me. It just opens one of the files.

I think this is a good feature to have. I'll see if I can figure out how to to.
